name: dox_builder
description: Dox builder for dox framework
version: 0.0.5
repository: https://github.com/dartondox/dox_builder
homepage: https://dartondox.dev

environment:
  sdk: '>=2.19.0 <3.1.0'

dependencies:
  build: ^2.4.0
  source_gen: ^1.3.1
  analyzer: ^5.12.0
  dox_annotation: ^0.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
